name: Build and Release Parx
run-name: ${{ github.actor }} is building and releasing the updated version of Parx
on: [push, pull_request]

jobs:
  create-parx-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Access frontend folder
        run: cd Parx

      - name: Install necessary packages
        uses: bahmutov/npm-install@v1

      - name: Prebuild application
        uses: mikeal/npx@master
        with:
          args: "expo prebuild"

      - name: Access android folder and build application
        run: cd android; ./gradlew assembleRelease
